---
- name: Install base packages
  hosts: localhost
  become: true

  tasks:
  - name: Add Hashicorp repo
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo

  - name: Install the required packages
    yum: 
      name: "{{ item.name }}"
      gpcheck: "{{ item.gpgcheck|default(omit) }}"
      state: latest
    with_items:
      - { name: wget }
      - { name: yum-utils }      
      # - { name: terraform }      
      - { name: docker }      
      # - { name: nginx }      
      - { name: jq }
      # - { name: vault }
      - { name: java-11-amazon-corretto-headless }      
      

  - name: Add the user 'ec2-user' with a group of 'docker'
    ansible.builtin.user:
      name: ec2-user
      comment: ec2-user
      group: docker     
      append: yes 

  - name: Start service docker, if not started
    ansible.builtin.service:
      name: docker
      state: restarted
      enabled: yes

  - name: Start service nginx, if not started
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Confirm that 200 OK response is returned
    uri:
      url: "https://google.com"
      status_code: 200
  # - name: terraform install
  #   unarchive:
  #     src: https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
  #     dest: /usr/bin
  #     remote_src: True
  - name: Install boto3
    ansible.builtin.pip:
      name: boto3
      extra_args: --user

  - name: Install kafka-python
    ansible.builtin.pip:
      name: kafka-python
      extra_args: --user




