---
- name: Install base packages
  hosts: localhost
  become: true

  vars: 
    - installation_dir : /usr/local/kafka 
    # - installation_dir : /opt/kafka

  tasks:
  - name: Add Hashicorp repo
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo

  - name: Install the required packages
    yum: 
      name: "{{ item.name }}"
      gpcheck: "{{ item.gpgcheck|default(omit) }}"
      state: latest
    with_items:
      - { name: wget }
      - { name: yum-utils }      
      # - { name: terraform }      
      - { name: docker }      
      # - { name: nginx }      
      - { name: jq }
      # - { name: vault }
      - { name: java-11-amazon-corretto-headless }      
      - { name: python3 }
      - { name: nc }      
      - { name: python-pip }      
            

  - name: Add the user 'ec2-user' with a group of 'docker'
    ansible.builtin.user:
      name: ec2-user
      comment: ec2-user
      group: docker     
      append: yes 

  - name: Start service docker, if not started
    ansible.builtin.service:
      name: docker
      state: restarted
      enabled: yes

  # - name: Start service nginx, if not started
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes
  
  # - name: Confirm that 200 OK response is returned
  #   uri:
  #     url: "https://google.com"
  #     status_code: 200

  # - name: terraform install
  #   unarchive:
  #     src: https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
  #     dest: /usr/bin
  #     remote_src: True

  - name: Install boto3
    ansible.builtin.pip:
      name: boto3
      extra_args: --user

  - name: Install kafka-python
    ansible.builtin.pip:
      name: kafka-python
      extra_args: --user

  - name: Create a group 
    become: yes
    group:
      name: kafka
      state: present
  - name: Create an user 
    become: yes
    user:
      name: kafka
      state: present
      group: kafka
  - name: Create a Directory 
    become: yes
    file:
      path: "{{installation_dir}}"
      state: directory
      mode: 0755
      owner: kafka
      group: kafka
  - name: Download Kafka and Unzip 
    become: yes
    become_user: kafka
    unarchive:
      src: https://archive.apache.org/dist/kafka/2.6.2/kafka_2.13-2.6.2.tgz
      dest: "{{installation_dir}}"
      mode: 0755
      remote_src: yes
  - name: Move all the files to parent Directory
    become: yes
    become_user: kafka
    shell:
      mv {{installation_dir}}/kafka_*/* {{installation_dir}}/.




