---
- name: Install base packages
  hosts: localhost
  become: true

  tasks:
  - name: Add Hashicorp repo
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo

  - name: Install the required packages
    yum: 
      name: "{{ item.name }}"
      gpcheck: "{{ item.gpgcheck|default(omit) }}"
      state: latest
    with_items:
      - { name: wget }
      - { name: yum-utils }      
      - { name: terraform }      
      - { name: docker }      
      - { name: nginx }      
      - { name: jq }

  - name: Add the user 'ec2-uer' with a group of 'docker'
    ansible.builtin.user:
      name: ec2-user
      comment: ec2-user
      group: docker     
      append: yes 

  - name: Start service docker, if not started
    ansible.builtin.service:
      name: docker
      state: restarted
      enabled: yes

  - name: Start service nginx, if not started
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Setup AWS Config file
    command:
      cmd: aws secretsmanager get-secret-value --secret-id usercdk-675716041761 --region us-east-2 --query SecretString | sed 's/["{}\]//g' | sed 's/:/,/g' | awk -F ',' '{print "aws_access_key_id = " $2}' >> /home/ec2-user/.aws/credentials
      cmd: 
      cmd: aws secretsmanager get-secret-value --secret-id usercdk-675716041761 --region us-east-2 --query SecretString | sed 's/["{}\]//g' | sed 's/:/,/g' | awk -F ',' '{print "aws_secret_access_key = " $4}' >> /home/ec2-user/.aws/credentials
      cmd: echo "[profile demo]" >> /home/ec2-user/.aws/config
      cmd: echo "region = us-east-2" >> /home/ec2-user/.aws/config

  # - name: terraform install
  #   unarchive:
  #     src: https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
  #     dest: /usr/bin
  #     remote_src: True



