---
- name: Install nginx
  hosts: localhost
  become: true

  tasks:
  # - name: Add epel-release repo
  #   yum:
  #     name: epel-release
  #     state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  # - name: Insert Index Page
  #   template:
  #     src: index.html
  #     dest: /usr/share/nginx/html/index.html

  # - name: Start NGiNX
  #   service:
  #     name: nginx
  #     state: started

#  - name: Yum Install Packages
#    yum: name={{item}} state=latest
#    with_items:
#       - wget
  - name: Add Hashicorp repo
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo

  - name: Install the required packages
    yum: 
      name: "{{ item.name }}"
      gpcheck: "{{ item.gpgcheck|default(omit) }}"
      state: latest
    with_items:
      - { name: wget }
      - { name: yum-utils }      
      - { name: terraform }      
      

  # - name: terraform install
  #   unarchive:
  #     src: https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
  #     dest: /usr/bin
  #     remote_src: True



